languageCode: en-us
title: tinylog 2
baseURL: https://tinylog.org/v2/
theme: tinylog-theme
timeZone: Europe/Berlin
disableHugoGeneratorInject: true
publishDir: ./public/v2

params:
  maxMajorVersion: 2
  stableVersion: 2.7.0
  previewVersion: 2.7.0
  size: 200036

permalinks:
  /documentation: /:filename
  /news: /:year/:month/:title

disableKinds:
  - taxonomy
  - term
  - RSS

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
